version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev_awbc_user
      POSTGRES_DB: awbc
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
